app/controllers/locomotive/concerns/token_authentication_controller.rb

please, merge it asap
without this small fix engine just did not work for me with the latest version of SimpleTokenAuthentication
see Gemfile.lock  below:
GIT
remote: git://github.com/locomotivecms/custom_fields.git
revision: 15cceb66ed22e96af57b5cacc1f131665997ab50
branch: mongoid_4
specs:
custom_fields (2.4.0.rc1)
activesupport (~> 4.2.0)
carrierwave-mongoid (~> 0.7.1)
monetize (~> 1.1.0)
mongoid (~> 4.0.0)
PATH
remote: /Users/dmitry/Projects/locomotivecms/engine
specs:
locomotive_cms (3.0.0)
RedCloth (~> 4.2.8)
actionmailer-with-request (~> 0.4.0)
autoprefixer-rails (~> 5.0.0.2)
backbone-on-rails (~> 1.1.2.0)
bootstrap-kaminari-views (~> 0.0.5)
bootstrap-sass (~> 3.3.3)
carrierwave-mongoid (~> 0.7)
cells (~> 3.11.3)
codemirror-rails (~> 4.8)
compass-rails (= 2.0.4)
devise (~> 3.4.1) …

fixed unsafe_token_authentication_params: made it select email from db

---

app/uploaders/locomotive/theme_asset_uploader.rb
lib/locomotive/carrierwave.rb
lib/locomotive/carrierwave/asset.rb

Seems latest fontawesome is now supporting woff2. Just added woff2 support to engine so I could wagon push.

add woff2 to acceptable mime types

---

config/locales/carrierwave.ru.yml

There is one extra space between "не" and "допустимый". Trust me, I'm russian.

Extra spaces removed.

---

config/initializers/uploaded_file.rb
spec/lib/uploaded_file_spec.rb

Added to_liquid method for ActionDispatch::Http::UploadedFile to allow for additional handling of uploaded files beyond using the public submission URL.

Added to_liquid method for ActionDispatch::Http::UploadedFile class

---

lib/locomotive/steam_adaptor.rb

Correctly merge the credentials as part of all client options into the steam
configuration hash. This allows adaption of relevant Mongoid options by
the steam client.
`:username` and `:password` were not extracted from the `:options` hash correctly which entirely broke authentication with MongoDB. Now additional keys like `:auth_source` and `:max_pool_size` are also passed to steam. I am currently preparing another PR on steam that will use these additional options for configuring the `Mongo::Client` accordingly.

Pass all configuration options to steam adapter

---

lib/locomotive/steam_adaptor.rb

To avoid logging into the root directory of the application and allow integration into other logging schemes. (in my case to allow deployment via NixOps)

add LOCOMOTIVE_STEAM_LOG env var

---

app/assets/javascripts/locomotive/views/inputs/rte/link_view.js.coffee
app/assets/javascripts/locomotive/views/inputs/rte/table_view.js.coffee
app/assets/javascripts/locomotive/views/inputs/rte_view.js.coffee.erb
app/assets/stylesheets/locomotive/old/form/_popover.scss

The popovers were being positioned like this:
This changes make them position at the bottom of the button, so they can be closed.

Change positioning of wysiwyg popover options

---

vendor/assets/javascripts/locomotive/wysihtml5x-toolbar.js

Patch wysihtml5 so that Shift+Enter inserts a `<br>`. This is consistent to the behavior of Locomotive 2, which used _tinyMCE_.

Changed wysihtml5 so that Shift+Enter inserts <br> like in Locomotive 2

---

lib/locomotive/dragonfly.rb
spec/helpers/locomotive/shared/accounts_helper_spec.rb

Hey @did. First off, thank you for all of your hard work on Locomotive. I've been using it for many years now and I hope you know how much I appreciate all that you have done.
I'm creating this PR in case you want to release another `3.2.x` that fixes #1197. This patch was necessary for me to be able to use the admin interface on Heroku on `ruby 2.3`. It just cherry-picks your earlier commit into the `3.2.x` branch.
I would update to the `3.3.x` branch, but unfortunately it's not compatible with the `platform-api` gem, as there is a conflict over the `moneta` gem. `locomotivecms 3.3.x` uses `locomotivecms_steam 1.3.0` which uses `moneta 1.0.0`, while even the most recent `platform-api 2.1.0` uses `moneta 0.8.1`.
Thank you again.

fix issue #1197 (account.avatar.url is a frozen string)

---

app/api/locomotive/api/entities/site_entity.rb
app/api/locomotive/api/forms/site_form.rb
app/api/locomotive/api/resources/current_site_resource.rb
app/api/locomotive/api/resources/site_resource.rb
app/models/locomotive/concerns/site/access_points.rb
app/policies/locomotive/site_policy.rb
app/views/locomotive/current_site/form/_access_points.html.slim
config/locales/simple_form.en.yml
lib/locomotive/regexps.rb
spec/api/locomotive/api/entities/site_entity_spec.rb
spec/api/locomotive/api/forms/site_form_spec.rb
spec/models/locomotive/concerns/site/access_points_spec.rb
spec/models/locomotive/site_spec.rb

These are the changes to the ```engine``` library that are needed to allow for per-site asset hosts.
This augments the default behavior of setting a single asset host at the ```engine``` level.
```engine```, ```steam```, and ```wagon``` all require changes for this feature to work:
- https://github.com/interhive/engine/tree/feature-per-site-asset-host
- https://github.com/interhive/steam/tree/feature-per-site-asset-host
- https://github.com/interhive/wagon/tree/feature-per-site-asset-host
Please review and let me know if I need to make any changes.
Thanks,
Chris

feature: per-site asset host

---

app/policies/locomotive/site_policy.rb

In a project using ruby-2.4.1, engine-3.3.0.rc3 and sidekiq-5.0.4, when I run `bundle exec sidekiq` I get the following error:
```bash
superclass mismatch for class Scope
/korujas/vendor/gems/engine/app/policies/locomotive/site_policy.rb:4:in `<class:SitePolicy>'
```

Avoids ambiguity

---

app/api/locomotive/api/middlewares/logger_middleware.rb

Some 3rd party gems may add symbols as keys into `env` in their middlewares.

Check env key type in LoggerMiddleware

---

app/views/locomotive/shared/_head.html.slim

Tabs are only so wide. Currently the unique identifier (site title) is at the end of the title and getting snipped making the tab title useless when you have multiple sites open in different tabs. This PR swaps the order so the the unique identifier is always visible with the redundant CMS name getting snipped when width is not available.

Change title format

---

app/views/locomotive/shared/_sidebar.html.slim
app/views/locomotive/shared/sidebar/_content_types.html.slim
app/views/locomotive/shared/sidebar/_pages.html.slim

Before: In the sidebar, when active/selected, Models and Pages collapse lists default to closed when page load.
After: In the sidebar, when active/selected, Models or Pages collapse lists are now open when page loads.

Open sidebar collapse menus when active

---

app/assets/stylesheets/locomotive/new/_sidebar.scss

Maybe it would be better for this to be a global css rule? Not sure where to put it in that case.

Change cursor to `move` on draggable pages within Sidebar

---

config/webpack/production.js

After running the production build I was getting an error
```
global is not defined
```
This problem did not appear in the development build, changing the webpack production `config.target` from `node` to `web` solves the issue.

Fix webpack production build error

---

lib/generators/locomotive/install/templates/carrierwave_aws.rb

As documented here https://github.com/sorentwo/carrierwave-aws/issues/40 this is the way to support another S3 storage provider.
/cc @sebastienbeau

Support different endpoint for S3 storage

---

app/jobs/locomotive/send_pony_email_job.rb

Not sure if it's the right fix, but without these chaneges it's not possible to use a smtp server that does not require user/pwd

Fixing send_mail if smtp is configured with blank user/pwd

---

app/uploaders/locomotive/theme_asset_uploader.rb

I'm setting up some header with background video.
It requires three formats : .mp4 .ogv and .webm that is missing

Allow .webm theme asset upload

---

app/models/locomotive/concerns/asset/vignette.rb

If you upload a broken image but considered as an image
the height and width will be empty and the comparison
with a number for checking the size will fail
Return the origin url if height width are nill

width and height can be empy if dragonfly fail

---

Gemfile
Gemfile.lock
lib/locomotive/mongoid/patches.rb
spec/factories/site.rb
spec/system/edit_site_spec.rb

**Explanation**:
The Rails ActionView inputs get the value of a field from the <FIELD>_before_type_cast method if it exists.
In Mongoid 7, the Mongoid core team implemented the `_before_type_cast?` / `_before_type_cast` for ALL the fields including the localized ones.
Incidentally, it breaks the form inputs for localized fields. 
This patch restores the old behavior for localized fiels by implementing the X_came_from_user? method which makes the form inputs use the translated value of a field.

Localized fields don't render correctly in forms
